# buildspec.yml
version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region us-east-2)
  build:
    commands:
      - sbt test
      - sbt docker:publish
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - Dockerrun.aws.json
